apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql-epi-pvc
  name: postgresql-epi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
status: {}